name: "Bug Report"
description: "Report a reproducible bug to help us improve Jaseci."
title: "[Bug]: "
labels: ["Type: Bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug — your contribution helps make Jac better for everyone!
        Please fill out all sections carefully and in English. The more detail you provide, the faster we can reproduce and fix the issue.
        > Before submitting, search [existing issues](https://github.com/Jaseci-Labs/jaseci/issues) to avoid duplicates.

        ---

        ## Bug Details

  - type: dropdown
    id: component
    attributes:
      label: "Affected Package"
      description: "Which package in the Jaseci stack does this bug affect?"
      options:
        - "jaclang"
        - "jac-byllm"
        - "jac-client"
        - "jac-scale"
        - "jac-super"
        - "jaseci (meta-package)"
        - "LSP / IDE Integration"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - "Critical — Crashes / Data loss / Blocks all usage"
        - "High — Major feature broken, no workaround"
        - "Medium — Feature broken, workaround exists"
        - "Low — Minor inconvenience"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "A clear, one-sentence description of the bug."
      placeholder: "e.g. Walker fails with a TypeError when spawning on a node with inherited abilities."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Environment"

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      options:
        - "Ubuntu / Debian"
        - "macOS"
        - "Windows"
        - "Other Linux"
        - "Other"
    validations:
      required: true

  - type: input
    id: jac-version
    attributes:
      label: "Jac Version"
      description: "Run `jac -V` to get the version."
      placeholder: "e.g. 0.11.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: "Python Version"
      description: "Run `python --version` to get the version."
      placeholder: "e.g. 3.12.2"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Reproduction"

  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to Reproduce"
      placeholder: |
        1. Create a `.jac` file with minimal reproduction code:
           ```jac
           # minimal reproduction
           ```
        2. Run: `jac run <file>.jac`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      placeholder: "e.g. Should print `Hello, Jaseci!` and exit cleanly."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "Paste the full error output or stack trace."
      placeholder: |
        TypeError: 'NoneType' object is not iterable
        Traceback (most recent call last):
          File "...", line X, in say_hello
            ...
      render: shell
    validations:
      required: true
