name: "Bug Report"
description: "Report a reproducible bug to help us improve Jaseci."
title: "[Bug]: "
labels: ["Type: Bug"]
assignees: []
body:
  - type: dropdown
    id: component
    attributes:
      label: "Affected Package"
      description: "Which package in the Jaseci stack does this bug affect?"
      options:
        - "jaclang"
        - "jac-byllm"
        - "jac-client"
        - "jac-scale"
        - "jac-super"
        - "jaseci (meta-package)"
        - "LSP / IDE Integration"
        - "Other"
    validations:
      required: true

  - type: input
    id: component-other
    attributes:
      label: "If 'Other', specify the affected area"
      placeholder: "e.g. docs, release scripts, CI/CD"

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - "Critical — Crashes / Data loss / Blocks all usage"
        - "High — Major feature broken, no workaround"
        - "Medium — Feature broken, workaround exists"
        - "Low — Minor inconvenience"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      options:
        - "Ubuntu / Debian"
        - "macOS"
        - "Windows"
        - "Other Linux"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: jac-version
    attributes:
      label: "Jac Version"
      description: "Run `jac -V` to check. Select 'Older version' if yours is not listed."
      options:
        - "0.11.0"
        - "Older version"
    validations:
      required: true

  - type: input
    id: jac-version-older
    attributes:
      label: "Jac Version (if 'Older version' selected above)"
      placeholder: "e.g. 0.9.1"

  - type: dropdown
    id: python-version
    attributes:
      label: "Python Version"
      description: "Run `python --version` to check. Select 'Older version' if yours is not listed."
      options:
        - "3.13"
        - "3.12"
        - "3.11"
        - "3.10"
        - "3.9"
        - "Older version"
    validations:
      required: true

  - type: input
    id: python-version-older
    attributes:
      label: "Python Version (if 'Older version' selected above)"
      placeholder: "e.g. 3.8.12"

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "A clear, one-sentence description of the bug."
      placeholder: "e.g. Walker fails with a TypeError when spawning on a node with inherited abilities."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to Reproduce"
      placeholder: |
        1. Create `example.jac`:
           ```jac
           walker greet {
               can say_hello with `root entry {
                   print("Hello, Jaseci!");
               }
           }
           with entry { root spawn greet(); }
           ```
        2. Run: `jac run example.jac`
        3. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      placeholder: "e.g. Should print `Hello, Jaseci!` and exit cleanly."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "Paste the full error output or stack trace."
      placeholder: |
        TypeError: 'NoneType' object is not iterable
        Traceback (most recent call last):
          File "...", line X, in say_hello
            ...
      render: shell
    validations:
      required: true
