name: "Bug Report"
description: "Report a reproducible bug to help us improve Jaseci."
title: "[Bug]: "
labels: ["Type: Bug"]
assignees: []
body:
  - type: dropdown
    id: component
    attributes:
      label: "Affected Component"
      options:
        - "jaclang — Compiler / Type System"
        - "jaclang — Runtime / Interpreter"
        - "jaclang — Standard Library"
        - "jaclang — CLI (jac run, jac test, etc.)"
        - "jac-byllm — LLM Integration / by llm() syntax"
        - "jac-byllm — Semantic Strings (sem)"
        - "jac-client — JSX / Frontend Compilation"
        - "jac-client — Vite Bundling"
        - "jac-scale — Kubernetes / Deployment"
        - "jac-scale — Redis / MongoDB Integration"
        - "jac-scale — FastAPI / Server"
        - "jac-super — Rich CLI Output"
        - "jaseci — Meta-package / Install"
        - "LSP / IDE Integration"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - "Critical — Crashes / Data loss / Blocks all usage"
        - "High — Major feature broken, no workaround"
        - "Medium — Feature broken, workaround exists"
        - "Low — Minor inconvenience"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      options:
        - "Ubuntu / Debian"
        - "macOS"
        - "Windows"
        - "Other Linux"
        - "Other"
    validations:
      required: true

  - type: input
    id: jac-version
    attributes:
      label: "Jac Version"
      description: "Run `jac -V` to get the version."
      placeholder: "e.g. 0.8.3"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: "Python Version"
      description: "Run `python --version` to get the version."
      placeholder: "e.g. 3.12.2"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "A clear, one-sentence description of the bug."
      placeholder: "e.g. `jac run` crashes with a KeyError when using walkers with inherited archetypes."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to Reproduce"
      placeholder: |
        1. Create a `.jac` file with:
           ```jac
           # minimal reproduction
           ```
        2. Run `jac run <file>.jac`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "Paste the full error output or stack trace."
      render: shell
    validations:
      required: true
