name: "Bug Report"
description: "Report a reproducible bug to help us improve Jaseci."
title: "[Bug]: "
labels: ["Type: Bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: |
        ### Thank you for helping us improve Jaseci!
        To ensure we can address your report efficiently, please fill out all sections and provide as much detail as possible.
        Before submitting, search [existing issues](https://github.com/Jaseci-Labs/jaseci/issues) to avoid duplicates.

  - type: markdown
    attributes:
      value: "---"

  - type: input
    id: summary
    attributes:
      label: "Bug Summary"
      description: "A clear, one-sentence description of the bug."
      placeholder: "e.g. `jac run` throws a TypeError on valid code that worked in the previous version."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Environment"

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      options:
        - "macOS"
        - "Windows"
        - "Ubuntu"
        - "Debian"
        - "Fedora"
        - "Other Linux"
        - "Other"
    validations:
      required: true

  - type: input
    id: versions
    attributes:
      label: "Jac & Python Version"
      placeholder: "Jac 0.11.0 | Python 3.12.2"
    validations:
      required: true

  - type: input
    id: other-versions
    attributes:
      label: "Other Jaseci Stack Versions (leave blank if not installed)"
      placeholder: "jac-scale = 0.1.10 | jac-byllm = 0.5.0 | jac-client = 0.2.19"

  - type: markdown
    attributes:
      value: "---"

  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to Reproduce"
      placeholder: |
        1. Create a `.jac` file with minimal reproduction code:
           ```jac
           # minimal reproduction
           ```
        2. Run: `jac run <file>.jac`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      placeholder: "e.g. Should print `Hello, Alice` and exit with code 0."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "Paste the full error output or stack trace."
      placeholder: |
        ```
        TypeError: can only concatenate str (not "NoneType") to str
          File "test.jac", line 6, in say_hello
        ```
      render: shell
    validations:
      required: true
