name: "Feature Request"
description: "Propose a new feature or enhancement for Jaseci."
title: "[Feature]: "
labels: ["Type: Feature"]
assignees: []
body:
  - type: dropdown
    id: component
    attributes:
      label: "Target Package"
      description: "Which package in the Jaseci stack should this feature be added to?"
      options:
        - "jaclang"
        - "jac-byllm"
        - "jac-client"
        - "jac-scale"
        - "jac-super"
        - "jaseci (meta-package)"
        - "LSP / IDE Integration"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: input
    id: component-other
    attributes:
      label: "If 'Other', specify the target area"
      placeholder: "e.g. release scripts, CI/CD, tooling"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "Nice to have"
        - "Important"
        - "Critical / Blocking my work"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "Problem Statement"
      description: "What problem does this feature solve?"
      placeholder: "e.g. There is no way to pass context between walkers during graph traversal without relying on global state, which makes complex agentic flows hard to manage."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      placeholder: "e.g. Add a `ctx` parameter to `spawn` so walkers can receive context data directly when they are spawned on a node."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: "Example / Mockup"
      description: "Show how this feature would look in Jac code."
      placeholder: |
        ```jac
        walker visitor {
            can greet with node entry(ctx: dict) {
                print(ctx['message']);
            }
        }

        with entry {
            root spawn visitor(ctx={'message': 'Hello from context!'});
        }
        ```
