name: "Documentation"
description: "Report missing, incorrect, or unclear documentation."
title: "[Docs]: "
labels: ["Type: Documentation"]
assignees: []
body:
  - type: dropdown
    id: doc-issue-type
    attributes:
      label: "Type of Documentation Issue"
      options:
        - "Missing documentation — topic not covered"
        - "Incorrect or outdated — content is wrong"
        - "Unclear or confusing — hard to understand"
        - "Code example needed or broken"
        - "New feature needs docs"
        - "Tutorial / Guide request"
        - "API reference improvement"
    validations:
      required: true

  - type: dropdown
    id: doc-section
    attributes:
      label: "Documentation Section"
      options:
        - "Quick Guide — Getting Started"
        - "Quick Guide — Core Features"
        - "Tutorials"
        - "Reference — jaclang API"
        - "Reference — jac-byllm / LLM integration"
        - "Reference — jac-client / Frontend"
        - "Reference — jac-scale / Deployment"
        - "Reference — CLI commands"
        - "Community — Contributing"
        - "README / Install Instructions"
        - "Other"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: "Link to Page / File"
      placeholder: "e.g. https://www.jac-lang.org/docs/... or docs/reference/walkers.md"

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What is missing, incorrect, or needs improvement?"
    validations:
      required: true

  - type: textarea
    id: suggested-change
    attributes:
      label: "Suggested Change"
      description: "How should it be improved? (optional)"
