name: "Documentation"
description: "Report missing, incorrect, or unclear documentation."
title: "[Docs]: "
labels: ["Type: Documentation"]
assignees: []
body:
  - type: dropdown
    id: doc-issue-type
    attributes:
      label: "Issue Type"
      options:
        - "Missing — topic not covered"
        - "Incorrect or outdated — content is wrong"
        - "Unclear or confusing — hard to understand"
        - "Code example needed or broken"
        - "New feature needs docs"
        - "Tutorial / Guide request"
        - "API reference improvement"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: doc-section
    attributes:
      label: "Affected Section"
      description: "Which part of the Jaseci docs is this about?"
      options:
        - "Quick Guide — Getting Started"
        - "Quick Guide — Core Features"
        - "Tutorials"
        - "Reference — jaclang"
        - "Reference — jac-byllm / LLM integration"
        - "Reference — jac-client / Frontend"
        - "Reference — jac-scale / Deployment"
        - "Reference — CLI commands"
        - "Community — Contributing"
        - "README / Install Instructions"
        - "Other"
    validations:
      required: true

  - type: input
    id: doc-section-other
    attributes:
      label: "If 'Other', specify the section"
      placeholder: "e.g. release notes, examples, FAQ"

  - type: input
    id: location
    attributes:
      label: "Link to Page / File"
      placeholder: "e.g. https://www.jac-lang.org/docs/... or docs/reference/walkers.md"

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What is missing, incorrect, or needs improvement?"
      placeholder: "e.g. The reference page for `by llm()` doesn't explain how to handle cases where the model returns an unexpected type — there are no examples showing error handling or type constraints."
    validations:
      required: true

  - type: textarea
    id: suggested-change
    attributes:
      label: "Suggested Change"
      description: "How should it be improved? (optional)"
      placeholder: "e.g. Add a section under `by llm()` showing how to use `sem` strings to constrain model output types, with a working Jac code example."
